### ISSUE TITLE
[BUG] vm entries not being added to the correct inventory group

### ISSUE THREAD

**Issue by flyemsafe** [Qubinode/qubinode-installer#44]
**Describe the bug**
the task below in playbooks/roles/ansible-role-rhel7-kvm-cloud-init/tasks/post-config.yml 
should add the vms to the correct inventory, they are all being placed under the [dns] group.

```
- name: ensure host is added to inventory
  lineinfile:
    path: "{{ inventory_file }}"
    line: "{{ vm_name }}   ansible_host={{ vm_ip.stdout }} ansible_user={{ admin_user }}"
    insertafter: '{{ inventory_group }}'
    state: present
  register: update_inventory
  when: update_inventory and vm_ip.stdout is defined
```

**To Reproduce**
Run ansible-playbook playbooks/deploy_vms.yml

**Expected behavior**

**Screenshots**
```
[dns]
ocp-dns01   ansible_host=172.24.24.102 ansible_user=qubi
ocp-master01   ansible_host=172.24.24.106 ansible_user=qubi
ocp-node01   ansible_host=172.24.24.105 ansible_user=qubi
ocp-node02   ansible_host=172.24.24.114 ansible_user=qubi
ocp-infra01   ansible_host=172.24.24.118 ansible_user=qubi
ocp-infra02   ansible_host=172.24.24.116 ansible_user=qubi
ocp-lb01   ansible_host=172.24.24.113 ansible_user=qubi
```

**Additional context**
